[config]
default_to_workspace = false

[env]
HOST                = "0.0.0.0"
PORT                = 8443
DATABASE_USERNAME   = "f3"
DATABASE_PASSWORD   = "funfunfun"
DATABASE_NAME       = "f3"
DATABASE_PORT_OUTER = 5432
DATABASE_PORT_INNER = 5432

[tasks.set-env-docker.env]
DATABASE_HOST = "postgres"
DATABASE_PORT = "${DATABASE_PORT_INNER}"
DATABASE_URL  = "postgres://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?user=${DATABASE_USERNAME}&password=${DATABASE_PASSWORD}"

[tasks.set-env-local.env]
DATABASE_HOST = "localhost"
DATABASE_PORT = "${DATABASE_PORT_OUTER}"
DATABASE_URL  = "postgres://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?user=${DATABASE_USERNAME}&password=${DATABASE_PASSWORD}"

[tasks.before-build]
run_task = [
  { name  = [
      "compose-up-db",
      "migrate",
  ]  },
]

[tasks.compose-build-app]
extend = "set-env-local"
command = "docker"
cwd = "./f3-server"
args = [
  "compose", "build", "app", "--build-arg", "BUILDKIT_INLINE_CACHE=1", "${@}"
]

[tasks.run]
extend = "set-env-local"
dependencies = ["before-build"]
cwd = "./f3-server"
command = "cargo"
args = ["run", "${@}"]

[tasks.run-in-docker]
extend = "set-env-docker"
dependencies = ["before-build", "compose-build-app"]
command = "docker"
args = ["compose", "up", "-d", "app"]

[tasks.logs]
extend = "set-env-docker"
dependencies = ["before-build"]
command = "docker"
args = ["compose", "logs", "${@}"]

[tasks.build]
extend = "set-env-local"
dependencies = ["before-build"]
cwd = "./f3-server"
command = "cargo"
args = ["build", "${@}"]

[tasks.check]
extend = "set-env-local"
dependencies = ["before-build"]
cwd = "./f3-server"
command = "cargo"
args = ["check"]

[tasks.watch]
extend = "set-env-local"
dependencies = ["before-build"]
run_task = [{ name = ["fmt", "clippy", "test"] }]
watch = true

[tasks.fmt]
extend = "set-env-local"
cwd = "./f3-server"
command = "cargo"
args = ["fmt", "--all", "${@}"]

[tasks.clippy]
extend = "set-env-local"
cwd = "./f3-server"
command = "cargo"
args = ["clippy", "--all", "--all-targets", "${@}"]

[tasks.test]
extend = "set-env-local"
install_crate = { crate_name = "cargo-nextest", binary = "cargo", test_arg = [ "nextest", "--help"] }
install_crate_args = ["--locked"]
cwd = "./f3-server"
command = "cargo"
args = [
  "nextest", "run", "--workspace",
  "--status-level", "all", "--test-threads=1",
]

[tasks.clippy-ci]
dependencies = ["before-build"]
run_task = "clippy" 

[tasks.test-ci]
dependencies = ["before-build"]
run_task = "test" 

[tasks.migrate]
extend = "set-env-local"
install_crate = { crate_name = "sqlx-cli", binary = "sqlx", test_arg = "--help", version = "0.9.0" }
cwd = "./f3-server"
command = "sqlx"
args = ["migrate", "run", "--source", "crates/adapter_out_persistence/src/migration"]

[tasks.sqlx]
extend = "set-env-local"
install_crate = { crate_name = "sqlx-cli", binary = "sqlx", test_arg = "--help", version = "0.9.0" }
cwd = "./f3-server"
command = "sqlx"
args = ["${@}", "--source", "crates/adapter_out_persistence/src/migration"]

[tasks.psql]
extend = "set-env-local"
command = "docker"
args = [
  "run", "--it", "--rm",
  "--network", "host",
  "-v", "${PWD}:/work",
  "postgres:18", "psql", "${DATABASE_URL}",
  "-f", "/work/data/initial_setup.sql",
]

[tasks.compose]
extend = "set-env-docker"
command = "docker"
args = ["compose", "${@}"]

[tasks.compose-up-db]
extend = "set-env-docker"
command = "docker"
args = ["compose", "up", "-d", "db"]

[tasks.compose-down]
extend = "set-env-docker"
command = "docker"
args = ["compose", "down"]

[tasks.compose-remove]
extend = "set-env-docker"
command = "docker"
args = ["compose", "down", "-v"]

[tasks.debug-env]
extend = "set-env-docker"
script = '''
echo "PORT=${PORT}"
echo "DATABASE_URL=${DATABASE_URL}"
echo "DATABASE_NAME=${DATABASE_NAME}"
'''
