[package]
name = "infrastructure"
version = "0.1.0"
edition = "2024"

# 依存レイヤーはdomainのみ
[dependencies]
async-trait = { workspace = true }
sqlx = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
http-body-util = { workspace = true }
bytes = { workspace = true }
uuid = { workspace = true }
log = { workspace = true }
x25519-dalek = { workspace = true }
rust-crypto = { workspace = true }
rand = { workspace = true }
base64 = { workspace = true }
serde = { workspace = true }
serde_cbor = { workspace = true }

domain = { workspace = true }
