[workspace]
resolver = "2"
members = [
    "entrypoint",
    "crates/util",
    "crates/application",
    "crates/adapter_in_web", 
    "crates/adapter_out_persistence", 
    "crates/adapter_out_c2", 
]
default-members = ["entrypoint"]
exclude = ["test-tools"]

[workspace.package]
name = "f3-server"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
actix-web = { version = "4", features = ["openssl"] }
actix-session = { version = "0.11.0" }
actix-files = { version = "0.6.10" }
actix-cors = { version = "0.7.1" }
actix-web-httpauth = { version = "0.8.2" }
openssl = { version = "0.10" }
sqlx = { version = "0.9.0", features = ["runtime-tokio", "uuid", "chrono", "macros", "postgres", "migrate"] }
utoipa = { version = "5", features = ["actix_extras", "chrono", "uuid"] }
utoipa-swagger-ui = { version = "9", features = ["actix-web", "reqwest"] }
env_logger = { version = "0.11.11" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
serde_cbor = { version = "0.10" }
anyhow = { version = "1.0" }
thiserror = { version = "2.0.19" }
log = { version = "0.4" }
async-trait = { version = "0.1.91"}
futures = { version = "0.3" }
futures-util = { version = "0.3" }
base64 = { version = "0.23.0" }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7.19" }
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1.20", features = ["full"] }
http-body-util = { version = "0.1" }
bytes = { version = "1.12.1" }
uuid = { version = "1.24.0", features = ["v4"] }
x25519-dalek = { version = "3.0.0", features = ["getrandom"]}
rust-crypto = { version = "0.2.36" }
rand = { version = "0.10" }

util = { path = "crates/util" }
application = { path = "crates/application" }
adapter_in_web= { path = "crates/adapter_in_web" }
adapter_out_persistence= { path = "crates/adapter_out_persistence" }
adapter_out_c2= { path = "crates/adapter_out_c2" }

[profile.release]
lto = true
codegen-units = 1
