[package]
name = "entrypoint"
version.workspace = true
edition.workspace = true

[dependencies]
util = { workspace = true }
application = { workspace = true }
adapter_in_web = { workspace = true }
adapter_out_persistence = { workspace = true }
adapter_out_c2 = { workspace = true }

actix-web = { workspace = true }
tokio = { workspace = true }
env_logger = { workspace = true }
sqlx = { workspace = true }
