[package]
name = "application"
version.workspace = true
edition.workspace = true

[dependencies]
util = { workspace = true }

log = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
zeroize = { workspace = true }
