[package]
name = "adapter_out_persistence"
version.workspace = true
edition.workspace = true

[dependencies]
application = { workspace = true }
util = { workspace = true }

sqlx = { workspace = true }
async-trait = { workspace = true }
argon2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
