[package]
name = "usecase"
version = "0.1.0"
edition = "2024"

# 依存レイヤーはdomainのみ
[dependencies]
log = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }

domain = { workspace = true }
