[package]
name = "adapter_out_c2"
version.workspace = true
edition.workspace = true

[dependencies]
application = { workspace = true }
util = { workspace = true }

tokio = { workspace = true }
tokio-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
actix-web = { workspace = true }
http-body-util = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
x25519-dalek = { version = "3", features = ["getrandom", "static_secrets"] }
chacha20poly1305 = { version = "0.10" }
serde = { workspace = true }
serde_cbor = { workspace = true }
rand = { workspace = true }
bytes = { workspace = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }
