[package]
name = "adapter_in_web"
version.workspace = true
edition.workspace = true

[dependencies]
application = { workspace = true }
util = { workspace = true }

actix-web = { workspace = true }
actix-session = { workspace = true }
actix-files = { workspace = true }
actix-cors = { workspace = true }
actix-web-httpauth = { workspace = true }
openssl = { workspace = true }
futures-util = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
base64 = { workspace = true }
uuid = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
regex = { workspace = true }
